site_name: japanese-text-level

theme:
  name: material
  palette:
    scheme: slate

nav:
  # - Home: README.md
  - Home: index.md
  - Main: main.md

plugins:
  - mkdocstrings
  - search
  - include-markdown
